# Generated by Django 4.0.5 on 2022-06-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerente', models.CharField(max_length=20)),
                ('matricula', models.CharField(max_length=14)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('naturalidade', models.CharField(max_length=65)),
                ('filiacao', models.CharField(max_length=65)),
                ('curso', models.CharField(max_length=65)),
                ('periodo', models.CharField(max_length=35)),
                ('turno', models.CharField(max_length=65)),
                ('telefone', models.CharField(max_length=65)),
                ('especificar', models.TextField()),
                ('justificar', models.TextField()),
                ('feito', models.BooleanField(default=False)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requerimentos.tipo')),
            ],
        ),
    ]
