# Generated by Django 4.0.5 on 2022-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='turno',
            field=models.CharField(choices=[('m', 'Manhã'), ('t', 'Tarde'), ('n', 'Noite')], max_length=1),
        ),
    ]
