# Generated by Django 4.0.5 on 2022-07-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requerimentos', '0002_alter_requerimento_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimento',
            name='aluno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
