# Generated by Django 4.0.5 on 2022-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimentos', '0003_requerimento_anexo_alter_requerimento_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='tipo',
            field=models.CharField(choices=[('2° via', '2° via'), ('Aproveitamento de disciplina', 'Aproveitamento de disciplina'), ('Matricula fora do prazo', 'Matricula fora do prazo'), ('Declaração', 'Declaração'), ('Diploma', 'Diploma'), ('Reabertura de matricula', 'Reabertura de matricula'), ('Segunda chamada', 'Segunda chamada'), ('Reingresso', 'Reingresso'), ('Trancamento de disciplina', 'Trancamento de disciplina'), ('Outros', 'Outros')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
