# Generated by Django 4.0.5 on 2022-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requerimentos', '0005_remove_requerimento_feito_requerimento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='anexo',
            field=models.FileField(blank=True, upload_to='requerimento/anexo/%Y/%m/%d/'),
        ),
    ]
